<?php

/**
 * Implements hook_page_attachments().
 *
 * This adds our general library which contains common and layout CSS.
 *
 * This outputs the framework and component JavaScript settings to
 * drupalSettings.AmbientImpact.
 */
function ambientimpact_core_page_attachments(array &$page) {
	$page['#attached']['library'][] = 'ambientimpact_core/core';

	$jsSettings = [
		'framework'	=> [
			'cache'		=> [
				'assetKey'	=>
					\Drupal::state()->get('system.css_js_query_string'),
			],
		],
		'components'	=>
			\Drupal::service('plugin.manager.ambientimpact_component')
				->getComponentJSSettings()
	];

	$page['#attached']['drupalSettings']['AmbientImpact'] = $jsSettings;
}

/**
 * Implements hook_library_info_build().
 *
 * This returns the libraries defined in individual Ambient.Impact Components,
 * as returned by the 'plugin.manager.ambientimpact_component' service.
 *
 * @see \Drupal\ambientimpact_core\ComponentPluginManager::getComponentLibraries()
 *   Returns the value returned by this method.
 *
 * @see https://www.drupal.org/docs/8/creating-custom-modules/adding-stylesheets-css-and-javascript-js-to-a-drupal-8-module#dynamic-css-js
 */
function ambientimpact_core_library_info_build() {
	return
		\Drupal::service('plugin.manager.ambientimpact_component')
			->getComponentLibraries();
}

/**
 * Implements hook_element_info_alter().
 */
// function ambientimpact_core_element_info_alter(array &$info) {
// 	if (isset($info['toolbar'])) {
// 		$info['toolbar']['#attached']['library'][] =
// 			'ambientimpact_core/component.toolbar';
// 	}
// }
