<?php

/**
 * Implements hook_menu_local_tasks_alter().
 */
// function ambientimpact_web_menu_local_tasks_alter(
//   &$data, $routeName,
//   \Drupal\Core\Cache\RefinableCacheableDependencyInterface &$cacheability
// ) {
//   dpm($data);
//   // dpm($routeName);
//   // dpm($cacheability);
// }

/**
 * Implements hook_menu_local_actions_alter().
 */
// function ambientimpact_web_menu_local_actions_alter(&$localActions) {
//   dpm($localActions);
// }
