// -----------------------------------------------------------------------------
//   Ambient.Impact - UX - Off-canvas panel component demo
// -----------------------------------------------------------------------------

AmbientImpact.on([
  'offcanvas',
  'componentDemo',
], function(aiOffCanvas, aiComponentDemo) {
AmbientImpact.addComponent('offcanvasDemo', function(aiOffCanvasDemo, $) {
  'use strict';

  /**
   * The class of the hidden container generated by OffCanvas::getDemo().
   *
   * @type {String}
   */
  var panelsContainerClass = 'offcanvas-demo-panels';

  /**
   * An object containing information about the various demo panels.
   *
   * This will contain the following key/value pairs:
   * - $panel: the panel element, wrapped in a jQuery object.
   *
   * - $open: the open button, wrapped in a jQuery object.
   *
   * - actionLabel: the label to give the action (button) that opens this panel.
   *
   * - options: the options to pass to the aiOffCanvas component.
   *
   * - instance: the panel instance as returned by aiOffCanvas.init().
   *
   * @type {Object}
   */
  var panels = {};

  /**
   * The demo object to be passed to the aiComponentDemo component.
   *
   * The actions are generated based on the discovered panels generated by
   * OffCanvas::getDemo() in the back-end.
   *
   * @type {Object}
   */
  var demoObject = {
    machineName:  'offcanvas',
    actions:      {}
  };

  // Loop through all demo panels generated by the back-end OffCanvas::getDemo()
  // and build the panels object.
  $('.' + panelsContainerClass).children().each(function() {
    var $this = $(this);

    var panelDirection = $this.data('panel-direction');

    panels[panelDirection] = {
      $panel:       $this,
      actionLabel:  $this.data('action-label'),
      options:      {
        panelLocation: panelDirection
      }
    };

    demoObject.actions[panelDirection] = {
      label: panels[panelDirection].actionLabel
    };
  });

  // Attempt to create the demo actions with the built object, but don't proceed
  // if the demo wasn't successfully created.
  if (aiComponentDemo.addDemo(demoObject) === false) {
    return;
  }

  // Build the remaining panel options and prepare the panel elements to be used
  // by the off-canvas component.
  $.each(panels, function(panelDirection, panel) {
    if (!('$action' in demoObject.actions[panelDirection])) {
      return;
    }

    panel.options.panelSelector = '#' + panel.$panel.attr('id');

    panel.$open = demoObject.actions[panelDirection].$action;

    panel.options.openButton = panel.$open;

    panel.options.openButtonClasses = [
      // This selector needs to be unique to work correctly with Froffcanvas.
      'ambientimpact-component-demo__actions-action-button--' + panelDirection,
    ];

    panel.options.closeButtonClasses = ['material-button'];

    // Move the panel element out of the hidden container and into the main
    // layout area. Note that the data-off-canvas-main-canvas attribute is
    // created by Drupal and has no relation to this component.
    panel.$panel.appendTo('[data-off-canvas-main-canvas]');

    panel.instance = aiOffCanvas.init(panel.$panel, panel.options);
  });
});
});
