# Schema for ambientimpact_core.

# ambientimpact_core field formatter third-party settings schema.
field.formatter.third_party.ambientimpact_core:
  type: mapping
  label: 'Ambient.Impact: Core third party field formatter settings'
  mapping:
    play_icon:
      type: boolean
      label: 'Whether to display a provider/play icon over a video thumbnail.'
    use_photoswipe:
      type: boolean
      label: 'Whether to use PhotoSwipe on an image field.'
    use_photoswipe_gallery:
      type: boolean
      label: 'Whether to group all items in a field as a PhotoSwipe gallery.'
